# Generated by Django 6.0.5 on 2026-05-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_middle_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "resource",
                    models.CharField(choices=[("product", "Продукт")], max_length=50),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "Чтение"),
                            ("create", "Создание"),
                            ("update", "Обновление"),
                            ("delete", "Удаление"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("any", "Любой"), ("own", "Свой")], max_length=20
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Право",
                "verbose_name_plural": "Права",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "action", "scope"),
                        name="unique_permission_resource_action_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("admin", "Админ"),
                            ("manager", "Менеджер"),
                            ("user", "Пользователь"),
                            ("guest", "Гость"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="users.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.role",
                verbose_name="Роль",
            ),
        ),
    ]
